app/urls.py
from django.urls import path
from .views import products_list

urlpatterns = [
    path("products/", products_list, name="products_list"),
]

demo/urls.py
from django.contrib import admin
from django.urls import path,include
from app import views
from django.conf import settings
from django.conf.urls.static import static 



urlpatterns = [
    #path('admin/', admin.site.urls),
    path("reservationshow",views.showreservation,name="showreservation"),
    path("reservationaddnew",views.addnewreservation,name="adduser"),
    path("editres/<int:id>",views.editreservation,name="edit"),
    path("updateres/<int:id>",views.updatereservation,name="update"),
    path("deleteres/<int:id>",views.deletereservation,name="delete"),
    path("user",views.index2,name="index2"),
    path("clients",views.Clients,name="clients"),
    path("adduser",views.SignupPage,name="adduser"),
    path("about",views.About,name="about"),
    path("blog-single",views.BlogSingle,name="blog-single"),
    path("blog",views.Blog,name="blog"),
    path("car-single/<int:id>",views.CarSingle,name="car-single"),
    path("car",views.Car,name="car"),
    path("contact",views.Contact,name="contact"),
    #path("pricing",views.Pricing,name="pricing"), 
    path("services",views.Services,name="services"), 
    path("home", views.home, name='home'),
    path("", views.home, name='home'),
    path("addnew",views.addnew,name="addnew"),
    path("edit/<int:id>",views.edit,name="edit"),
    path("update/<int:id>",views.update,name="update"),
    path("delete/<int:id>",views.delete,name="delete"),
    path('login/',views.LoginPage,name='login'),
    path('signup/',views.SignupPage,name='signup'),
    path('logout/',views.LogoutPage,name='logout'),
    path('rent-a-car/',views.rent_a_car,name='rent-a-car'),
    path('scraptitle/', views.get_title, name='scraptitle'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User


class Personne(models.Model):
    Nom = models.CharField(max_length=100)
    PRENOM = models.CharField(max_length=100)
    CIN = models.CharField(max_length=100)
    Telephone = models.CharField(max_length=100)
    Adresse = models.CharField(max_length=100)
    class Meta:
        abstract = True


class EmployeeUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Nom = models.CharField(max_length=50)
    Prenom = models.CharField(max_length=50)
    Email = models.EmailField()
    Telephone = models.CharField(max_length=15)
    CIN = models.CharField(max_length=8)
    Address = models.CharField(max_length=100)

    def __str__(self):
        return self.Nom + ' ' + self.Prenom
    class Meta:
        db_table="EmployeeUser"

class Employe(Personne):
    Num_couverture = models.CharField(max_length=100)
    Salaire = models.FloatField()
    class Meta:
        db_table="Employe"

class Agence(models.Model):
    Nom = models.CharField(max_length=100)
    Telephone = models.CharField(max_length=100)
    IF = models.CharField(max_length=100)
    ICE = models.CharField(max_length=100)
    class Meta:
        db_table="Agence"
    def __str__(self):
        return self.Nom

class Voiture(models.Model):
    Nom = models.CharField(max_length=100)
    Mileage = models.CharField(max_length=100)
    Transmission = models.CharField(max_length=100)
    Fuel = models.CharField(max_length=100)
    Luggage = models.CharField(max_length=100)
    Matricule = models.CharField(max_length=100)
    Marque = models.CharField(max_length=100)
    Modele = models.CharField(max_length=100)
    Annee = models.IntegerField()
    NbPlaces = models.IntegerField()
    Couleur = models.CharField(max_length=100)
    PrixParJour = models.FloatField()
    IsAvailable = models.BooleanField()
    Image = models.ImageField(null=False,blank = False, upload_to="images/")
    Agence = models.ForeignKey(Agence, on_delete=models.CASCADE)

    class Meta:
        db_table="Voiture"
    def __str__(self):
        return self.Nom

class Reservation(models.Model):
    car = models.ForeignKey(Voiture, on_delete=models.CASCADE)
    pickup_location = models.CharField(max_length=100)
    dropoff_location = models.CharField(max_length=100)
    pickup_date = models.DateField()
    dropoff_date = models.DateField()
    pickup_time = models.CharField(max_length=100)

    def __str__(self):
        return f"Reservation #{self.pk}"

    class Meta:
        db_table = "Reservation"


class Reservation2(models.Model):
    DateRes = models.DateField()
    DateDebut = models.DateField()
    DateFin = models.DateField()
    Employe = models.ForeignKey(Employe, on_delete=models.CASCADE)
    Voiture = models.OneToOneField(Voiture,on_delete=models.CASCADE)

    class Meta:
        db_table="Reservation2"

class Client(models.Model):
    nom = models.CharField(max_length=50)
    prenom = models.CharField(max_length=50)
    email = models.EmailField()
    telephone = models.CharField(max_length=15)
    reservation = models.ForeignKey(Reservation, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nom} {self.prenom}"
    class Meta:
        db_table="Client"

app/templates/car/edit.html
{% extends "./base.html" %}
  
{% block title %}Add New Employee Records{% endblock title %}
  
{% block content %}
<div class="col-md-12">
    <form method="POST" class="post-form" action="/update/{{voiture.id}}"  enctype="multipart/form-data">  
    {% csrf_token %}  
    <div class="container">   
        <div class="col-12">  
            <h3>Update Details</h3>  
        </div> 
        <span><a href="/user" class="btn btn-primary">Back</a>
        </span>  
        <div class="mb-3"> 
            <label>ID:</label>  
            <input type="text" class="form-control" name="id" id="id_id" required maxlength="20" value="{{ voiture.id }}"/>    
        </div> 
        <div class="mb-3"> 
            <label>Nom:</label>  
            <input type="text" class="form-control" name="Nom" id="id_Nom" required maxlength="100" value="{{ voiture.Nom }}" />  
        </div> 
        <div class="mb-3"> 
            <label>Mileage:</label>  
            <input type="text" class="form-control" name="Mileage" id="id_Mileage" required maxlength="20" value="{{ voiture.Mileage }}"/>    
        </div> 
        <div class="mb-3"> 
            <label>Transmission:</label>  
            <input type="text" class="form-control" name="Transmission" id="id_Transmission" required maxlength="100" value="{{ voiture.Transmission }}" />  
        </div>         <div class="mb-3"> 
            <label>Fuel:</label>  
            <input type="text" class="form-control" name="Fuel" id="id_Fuel" required maxlength="20" value="{{ voiture.Fuel }}"/>    
        </div> 
        <div class="mb-3"> 
            <label>Luggage:</label>  
            <input type="text" class="form-control" name="Luggage" id="id_Luggage" required maxlength="100" value="{{ voiture.Luggage }}" />  
        </div>         <div class="mb-3"> 
            <label>Matricule:</label>  
            <input type="text" class="form-control" name="Matricule" id="id_Matricule" required maxlength="20" value="{{ voiture.Matricule }}"/>    
        </div> 
        <div class="mb-3"> 
            <label>Marque:</label>  
            <input type="text" class="form-control" name="Marque" id="id_Marque" required maxlength="100" value="{{ voiture.Marque }}" />  
        </div>         <div class="mb-3"> 
            <label>Modele:</label>  
            <input type="text" class="form-control" name="Modele" id="id_Modele" required maxlength="20" value="{{ voiture.Modele }}"/>    
        </div> 
        <div class="mb-3"> 
            <label>Annee:</label>  
            <input type="number" class="form-control" name="Annee" id="id_Annee" required maxlength="5" value="{{ voiture.Annee }}" />  
        </div>         <div class="mb-3"> 
            <label>NbPlaces:</label>  
            <input type="number" class="form-control" name="NbPlaces" id="id_NbPlaces" required maxlength="3" value="{{ voiture.NbPlaces }}"/>    
        </div> 
        <div class="mb-3"> 
            <label>Couleur:</label>  
            <input type="text" class="form-control" name="Couleur" id="id_Couleur" required maxlength="100" value="{{ voiture.Couleur }}" />  
        </div>         <div class="mb-3"> 
            <label>PrixParJour:</label>  
            <input type="number" class="form-control" name="PrixParJour" id="id_PrixParJour" required maxlength="20" value="{{ voiture.PrixParJour }}"/>    
        </div> 
        <div class="mb-3">
            <label for="id_IsAvailable">IsAvailable:</label>
            <select class="form-control" name="IsAvailable" id="id_IsAvailable" required>
              <option value="true" {% if not voiture.IsAvailable %}selected{% endif %}>True</option>
              <option value="false" {% if voiture.IsAvailable %}selected{% endif %}>False</option>
            </select>
          </div>
                         
          <div class="mb-3"> 
            <label>Image:</label>  
            <input type="file" class="form-control-file" name="Image" id="id_Image" accept="image/*"/>    
            {% if voiture.Image %}
                <img src="{{ voiture.Image.url }}" alt="Voiture Image" style="max-width: 200px;"/>
            {% endif %}
        </div>
        
        <div class="mb-3">
            <label for="id_Agence">Agence:</label>
            <select class="form-control" name="Agence" id="id_Agence" required >
              {% for agence in agences %}
                <option value="{{ agence.id }}" {% if agence.id == selected_agence %}selected{% endif %}>{{ agence.Nom }}</option>
              {% endfor %}
            </select>
          </div>
          
          
          
        <div class="mb-3"> 
            <button type="submit" class="btn btn-success btn-lg">Update</button>  
        </div> 
    </div>  
    </form>  
{% endblock content %}  

app/templates/car/index.html
{% extends "./base.html" %}
  
{% block title %}Add New Employee Records{% endblock title %}
  
{% block content %}

<div class="col-md-12"> 
    <h4>Add Car</h4>  
    <span><a href="/user" class="btn btn-primary">Back</a>
    </span>    
    <form method="POST" class="post-form" action="/addnew" enctype="multipart/form-data">  
    {% csrf_token %}  
    <div class="container">  
        <div class="col-12">  
        <h3>Enter Details</h3>  
        </div>    
     
        <div class="mb-3"> 
            <label>Nom:</label>  
            {{ form.Nom }}   
        </div> 
        <div class="mb-3"> 
            <label>Mileage:</label>  
            {{ form.Mileage }}   
        </div> 
        <div class="mb-3"> 
            <label>Transmission:</label>  
            {{ form.Transmission }}   
        </div> 
        <div class="mb-3"> 
            <label>Fuel:</label>  
            {{ form.Fuel }}   
        </div> 
        <div class="mb-3"> 
            <label>Luggage:</label>  
            {{ form.Luggage }}   
        </div> 
        <div class="mb-3"> 
            <label>Matricule:</label>  
            {{ form.Matricule }}   
        </div> 
        <div class="mb-3"> 
            <label>Marque:</label>  
            {{ form.Marque }}   
        </div> 
        <div class="mb-3"> 
            <label>Modele:</label>  
            {{ form.Modele }}   
        </div> 
        <div class="mb-3"> 
            <label>Annee:</label>  
            {{ form.Annee }}   
        </div> 
        <div class="mb-3"> 
            <label>NbPlaces:</label>  
            {{ form.NbPlaces }}   
        </div> 
        <div class="mb-3"> 
            <label>Couleur:</label>  
            {{ form.Couleur }}   
        </div> 
        <div class="mb-3"> 
            <label>PrixParJour:</label>  
            {{ form.PrixParJour }}   
        </div>  <div class="mb-3"> 
            <label>IsAvailable:</label>  
            {{ form.IsAvailable }}   
        </div>  <div class="mb-3"> 
            <label>Image:</label>  
            {{ form.Image }}   
        </div>
          
        <div class="mb-3"> 
            <label>Agence:</label>  
            {{ form.Agence }}   
        </div> 
        <div class="mb-3"> 
            <button type="submit" class="btn btn-primary">Submit</button>    
        </div> 
    </div>  
    </form>  
</div> 
{% endblock content %} 

app/templates/car/show.html
{% extends "./base.html" %}
  
{% block title %}Cars Records{% endblock title %}
  
{% block content %}
 <div class="col-md-12">
        <br>
        <span><a href="/addnew" class="btn btn-primary">Add New Car</a>
            <a href="/user" class="btn btn-primary">Cars</a>
            <a href="/adduser" class="btn btn-primary">Add New Employee</a>
            <a href="/logout" class="btn btn-primary">Logout</a></span>  
            <a href="/reservationshow" class="btn btn-primary">Reservation</a>
            <a href="/reservationaddnew" class="btn btn-primary">Add Reservation</a>
            <a href="/clients" class="btn btn-primary">Clients</a>

        <br>
        <br>
        <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
        <thead>
            <!--<th><input type="checkbox" id="checkall" /></th>-->
            <th>ID</th>
            <th>Nom</th>
            <th>Mileage</th>
            <th>Transmission</th>
            <th>Fuel</th>
            <th>Luggage</th>
            <th>Matricule</th>
            <th>Marque</th>
            <th>Modele</th>
            <th>Annee</th>
            <th>NbPlaces</th>
            <th>Couleur</th>
            <th>PrixParJour</th>
            <th>IsAvailable</th>
            <th>Image</th>
            <th>Agence</th>
            <th>Edit</th>
            <th>Delete</th>
        </thead>
        <tbody>
        {% for car in Voiture %}  
            <tr>  
            <!--<td><input type="checkbox" class="checkthis" /></td>-->
            <td>{{ car.id }}</td>  
            <td>{{ car.Nom }}</td>  
            <td>{{ car.Mileage }}</td>  
            <td>{{ car.Transmission }}</td>  
            <td>{{ car.Fuel }}</td>  
            <td>{{ car.Luggage }}</td>  
            <td>{{ car.Matricule }}</td>  
            <td>{{ car.Marque }}</td>  
            <td>{{ car.Modele }}</td>  
            <td>{{ car.Annee }}</td>  
            <td>{{ car.NbPlaces }}</td>  
            <td>{{ car.Couleur }}</td>  
            <td>{{ car.PrixParJour }}</td>  
            <td>{{ car.IsAvailable }}</td>  
            <td>
            {% if car.Image %}
            <img src="{{ car.Image.url }}" width="100">
            {% endif %}
            </td>  
            <td>{{ car.Agence.Nom }}</td>  
            <td><a href="/update/{{ car.id }}" class="btn btn-primary">Edit</a></td>
            <td><a href="/delete/{{ car.id }}" class="btn btn-danger">Delete</a></td>  
            </tr>  
        {% endfor %} 
        </tbody>
        </table>
        </div>
    </div>
{% endblock content %}